services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_UID: ${HOST_UID:-1000}
                HOST_GID: ${HOST_GID:-1000}
        ports:
            - "${PHP_FPM_PORT:-9000}:9000"
        container_name: dinheiro-api-app
        working_dir: /var/www/html
        environment:
            - HOST_UID=${HOST_UID:-1000}
            - HOST_GID=${HOST_GID:-1000}
        volumes:
            - ./:/var/www/html
        networks:
            - dinheiro-net

networks:
    dinheiro-net:
        driver: bridge

volumes:
    dinheiro-mariadb:
